package ch.rupfizupfi.deck.testrunner;

import ch.rupfizupfi.deck.data.TestResult;
import ch.rupfizupfi.deck.device.HardwareModeInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;

public class TestRunnerThread {
    private static final Logger logger = LoggerFactory.getLogger(TestRunnerThread.class);
    private final TestRunnerFactory testRunnerFactory;
    private final MotorSafetyController motorSafetyController;
    private final HardwareModeInfo hardwareModeInfo;
    private volatile boolean running = false;
    private TestResult testResult;
    private AbstractTest test;
    private TestLogger testLogger;
    private Thread thread;

    public TestRunnerThread(TestRunnerFactory testRunnerFactory, MotorSafetyController motorSafetyController,
                            HardwareModeInfo hardwareModeInfo) {
        this.testRunnerFactory = testRunnerFactory;
        this.motorSafetyController = motorSafetyController;
        this.hardwareModeInfo = hardwareModeInfo;
    }

    protected void run() {
        try {
            // Sleep for 50ms to allow the client to set up the websocket connection
            Thread.sleep(50);
            testLogger.log("init test " + testResult.testParameter.type);
            test = switch (testResult.testParameter.type) {
                case "cyclic" -> testRunnerFactory.createTestRunner(CyclicTest.class, testResult, testLogger);
                case "timeCyclic" -> testRunnerFactory.createTestRunner(TimeCyclicTest.class, testResult, testLogger);
                case "destructive" -> testRunnerFactory.createTestRunner(DestructiveTest.class, testResult, testLogger);
                default -> test;
            };

            if (test != null) {
                test.runStartupChecks();
                test.setup();
                test.getContext().processSignals();
            }
        } catch (InterruptedException e) {
            testLogger.log("interrupt test " + testResult.testParameter.type);
            logger.error("TestRunner Thread interrupted", e);
        } catch (FinishTestException ignored) {
        } catch (Exception e) {
            // getClass() alone renders as "class java.lang.IllegalStateException" in the test log
            testLogger.log("error: " + e.getClass().getSimpleName() + ", " + e.getMessage());
            testLogger.log("error test " + testResult.testParameter.type);
            logger.error("Exception occurred during test", e);
        } finally {
            if (test != null) {
                try {
                    test.cleanup();
                    test.destroy();
                } catch (Exception e) {
                    testLogger.log("error: " + e.getClass().getSimpleName() + ", " + e.getMessage());
                    logger.error("Exception during cleanup/destroy", e);
                    retryShutdownOnException();
                }
            }
            this.test = null;
            this.running = false;
        }
    }

    public void startThread(TestResult testResult) {
        if (!running) {
            try {
                this.running = true;
                this.test = null;
                // a latch left behind by the previous run would otherwise refuse to energize
                this.motorSafetyController.clearStopLatch();
                this.testResult = testResult;
                this.testLogger = testRunnerFactory.createLogger(testResult);
                this.testLogger.begin();
                announceHardwareMode();
                this.thread = new Thread(this::run, "TestRunnerThread");
                this.thread.start();
            } catch (IOException e) {
                logger.error("IOException occurred while starting the thread", e);
            }
        }
    }

    /**
     * Names the hardware mode on every single run, to the server log and to the operator's test log.
     * Unconditional and not configurable: an annunciation an operator can turn off is one that will
     * be off on the day a simulated trace is mistaken for a real one.
     */
    private void announceHardwareMode() {
        if (hardwareModeInfo.isSimulated()) {
            String warning = "SIMULATED HARDWARE - no load cell, no drive. This run measures nothing;"
                    + " its force trace is generated by a plant model and is not material data.";
            logger.warn(warning);
            testLogger.log(warning);
        } else {
            logger.info("hardware mode: {}", hardwareModeInfo.modeName());
            testLogger.log("hardware mode: " + hardwareModeInfo.modeName());
        }
    }

    public void stopThread() {
        if (this.running) {
            // test is still null during the startup window and after a failed setup(),
            // the stop must not throw there
            AbstractTest currentTest = this.test;
            TestContext currentContext = currentTest != null ? currentTest.getContext() : null;
            if (currentContext != null) {
                currentContext.sendSignal(0);
            }
            try {
                this.thread.join(1000);
                if (this.thread.isAlive()) {
                    this.thread.interrupt();
                    this.thread.join();
                }
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            } finally {
                if (this.testLogger != null) {
                    this.testLogger.end();
                }
                this.testLogger = null;
                this.test = null;
            }
        }
    }

    public boolean isRunning() {
        return this.running;
    }

    public TestResult getTestResult() {
        return testResult;
    }

    protected void retryShutdownOnException() {
        try {
            if (test != null) {
                test.destroy();
            }
        } catch (Exception ignored) {
            test = null;
            System.gc();
        }

        SafeStopResult result = motorSafetyController.safeStop("cleanup failed");
        if (result.coasting()) {
            // Already an emergency path, so still worth a line even though the drive answered.
            logger.warn("Emergency stop de-energized the drive, motor still coasting at {} rpm", result.motorSpeedRpm());
        } else if (result.needsOperatorAttention()) {
            logger.error("Emergency stop could not be verified: {}", result.detail());
        }
    }
}
