    insert into application_user (version, id, username,name,hashed_password) values (1, '1','user','Base User','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe')
insert into user_roles (user_id, roles) values ('1', 'USER')
insert into application_user (version, id, username,name,hashed_password) values (1, '2','admin','Admin User','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.')
insert into user_roles (user_id, roles) values ('2', 'USER')
insert into user_roles (user_id, roles) values ('2', 'ADMIN')

insert into gear_type (version, id, name) values (1, '1', 'shackle'), (1, '2', 'softshackle'), (1, '3', 'leash'), (1, '4', 'Leashrope'), (1, '5', 'rope'), (1, '6', 'cable'), (1, '7', 'Leashring'), (1, '8', 'Carabiner'), (1, '9', 'industrial sling'), (1, '10', 'climbing sling'), (1, '11', 'seewn')
insert into gear_standard (version, id, name) values (1, '1', 'EN362:2004'), (1, '2', 'ISA:52:2022'), (1, '3', 'UIAA121')
insert into material (version, id, name) values (1, '1', 'multi'), (1, '2', 'Polyamid'), (1, '3', 'Polyester'), (1, '4', 'Steel'), (1, '5', 'Aluminium'), (1, '6', 'Dyneema (UHMW-PE)'), (1, '7', 'Kevlar'), (1, '8', 'Hemp')
insert into customer (version, id, organization, firstname, lastname, email, street, code, location, country) values (1, '1', 'Climbing Club', 'John', 'Doe', 'john.doe@swiss-slackline.ch', 'Bahnhofstrasse 1', '8000', 'Zürich', 'Switzerland')